keys:
  # Users
  - &users:
    - &joka 7A0AF5B9AABC2CC6
  # Hosts
  - &hosts:
    - &alcedo age1frx3zkwt6qmnnwq5tz2mvylf7ry7ft4vzahs4ajlzcxx3l45950qc0k40x
    - &hirundo age1uhqk26zf6qn35y745lgqy296nlapdjz2hyazdy2a5yg6mw4303dss96629
    - &falco age1uwlzhmu3pw3rzpjtj5gu07qxge9tvr5vsq4995xxy7d4mtw7cugsh7d709
    - &regulus age1qcjfexjn80d3qfuu04k98yxqez7ujary6e4720506afh4dyg6eessp3208
    - &strix age1nuvx2zd6keg07mjt8n88rxzuavuzs75yzydy477ae6fyg4g4eu4q09k2jz
creation_rules:
  - path_regex: hosts/strix/secrets.ya?ml$
    key_groups:
    - age:
      - *strix
      pgp:
      - *joka
  - path_regex: hosts/falco/secrets.ya?ml$
    key_groups:
    - age:
      - *falco
      pgp:
      - *joka
  - path_regex: hosts/hirundo/secrets.ya?ml$
    key_groups:
    - age:
      - *hirundo
      pgp:
      - *joka
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *alcedo
      - *hirundo
      - *falco
      - *regulus
      - *strix
      pgp:
      - *joka