# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  inputs,
  modulesPath,
  wallpapers,
  ...
}: {
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  boot.kernelModules = ["kvm-intel"];
  boot.resumeDevice = "/dev/disk/by-label/system";
  boot.kernelParams = ["resume_offset=23078144"];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  theme = {
    wallpaper = wallpapers.astronaut-minimalism;
    colorscheme = {
      type = "tonal-spot";
      source = config.theme.wallpaper;
    };
  };
}
